### ISSUE TITLE
Organize Folders & Bookmarks

### ISSUE THREAD

**Issue by henrybelk** [somethingTacos/ChromeManagedBookMarksEditor#1]
Hello,

Great tool. It would be great to either be able to reorganize by a button or a drag and drop for folders and bookmarks. Or an alphabetical sort button.

Thanks

**Comment by somethingTacos** [comment]
I am implementing drag and drop into the next release. 

I don't currently have plans to add sorting, but I might add it in the future after I finish the current update.

**Comment by somethingTacos** [comment]
I have implemented a basic form of drag and drop. It isn't great, but Avalonia doesn't have proper support for it as far as I know.

It should at least allow you to move things around a bit, albeit a bit clunkaly...

https://github.com/somethingTacos/ChromeManagedBookMarksEditor/releases/tag/3.0
