### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by henrybelk** [somethingTacos/ChromeManagedBookMarksEditor#2]
Hello,

It seems the tool removes special characters (dash and parenthesis) when serialize is pushed. I can put the characters back in manually in the output in the GPO and it works correctly. But then if I need to edit and paste the existing in, it will wipe out the characters.

Thanks

**Comment by somethingTacos** [comment]
Next branch now uses proper json serialization and no longer attempts to sanitize the json. So this will be fixed when I release an updated version sometime soon. Figured it's probably time to fix this mess of a project...

**Comment by somethingTacos** [comment]
This has been fixed in the new version of this tool.

https://github.com/somethingTacos/ChromeManagedBookMarksEditor/releases/tag/3.0
