### ISSUE TITLE
Button to sort links in alphabetical order

### ISSUE THREAD

**Issue by jjmg84** [somethingTacos/ChromeManagedBookMarksEditor#7]
Hi, good job, it will be great if the application has a button to sort the links and child folders in alphabetical order.

Thanks!

**Comment by jffortier249** [comment]
Yes good ideal, sort folders, sort only URL within a folder.

**Comment by somethingTacos** [comment]
you can get this feature in the latest release
https://github.com/somethingTacos/ChromeManagedBookMarksEditor/releases/tag/3.1
